### PR TITLE
V2 Upgrade Guide

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by lmajano** [comment]
is this ready to go @elpete ??

**Comment by elpete** [comment]
No, that's why it's in draft.  I helped upgrade a project the other day and noticed there was no official migration guide.  This was my placeholder so we could fill it in.

**Comment by lmajano** [comment]
Remember we have the official docs now too. https://coldbox-mailservices.ortusbooks.com/

**Comment by elpete** [comment]
I was not aware of that.  Perhaps we remove the documentation from the readme so it's more obvious where to go look?

**Comment by lmajano** [comment]
Do you want me to do that or you have something in mind?

**Pull request closed without merging**
